# Day 19 - Performance Measures

**Topic:** Confusion Matrix, Precision, Recall, F1 Score, and Decision Thresholds  
**Book:** *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow* (Ch. 3)

### Learning Goals
- Understand **TP, TN, FP, FN**
- Build and interpret a **confusion matrix**
- Calculate **precision, recall, and F1-score**
- Explore **decision thresholds**
- Understand the **precision/recall trade-off**

## 1. Import Libraries

We will use a small binary classification example.

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

## 2. Create Example Predictions

Suppose:
- `1` = Positive class
- `0` = Negative class

In [2]:
y_true = np.array([1,0,1,1,0,1,0,0,1,0])
y_pred = np.array([1,0,1,0,0,1,0,1,1,0])

print("Actual labels:   ", y_true)
print("Predicted labels:", y_pred)

Actual labels:    [1 0 1 1 0 1 0 0 1 0]
Predicted labels: [1 0 1 0 0 1 0 1 1 0]

## 3. Confusion Matrix

Rows = actual labels  
Columns = predicted labels

In [3]:
cm = confusion_matrix(y_true, y_pred)
cm_df = pd.DataFrame(
    cm,
    index=["Actual 0", "Actual 1"],
    columns=["Predicted 0", "Predicted 1"]
)
cm_df

          Predicted 0  Predicted 1
Actual 0            4            1
Actual 1            1            4

### Interpretation

- **TN** = correctly predicted negative
- **FP** = predicted positive but actually negative
- **FN** = predicted negative but actually positive
- **TP** = correctly predicted positive

In [4]:
tn, fp, fn, tp = cm.ravel()

print("True Negative (TN):", tn)
print("False Positive (FP):", fp)
print("False Negative (FN):", fn)
print("True Positive (TP):", tp)

True Negative (TN): 4
False Positive (FP): 1
False Negative (FN): 1
True Positive (TP): 4

## 4. Precision

**Question:** Of all predicted positives, how many were correct?

Formula:

Precision = TP / (TP + FP)

In [5]:
precision = precision_score(y_true, y_pred)
print("Precision:", round(precision, 3))

Precision: 0.8

**Meaning:** Higher precision means fewer false alarms.

## 5. Recall

**Question:** Of all actual positives, how many were found?

Formula:

Recall = TP / (TP + FN)

In [6]:
recall = recall_score(y_true, y_pred)
print("Recall:", round(recall, 3))

Recall: 0.8

**Meaning:** Higher recall means fewer missed positives.

## 6. F1 Score

F1 combines precision and recall.

Formula:

F1 = 2 * (Precision * Recall) / (Precision + Recall)

In [7]:
f1 = f1_score(y_true, y_pred)
print("F1 Score:", round(f1, 3))

F1 Score: 0.8

### Why F1?

Use F1 when:
- classes are imbalanced,
- and both precision and recall are important.

## 7. Decision Threshold

A classifier often predicts probabilities.  
Default threshold = **0.5**.

If probability ≥ threshold → predict **1**.

In [8]:
y_scores = np.array([0.95,0.10,0.85,0.40,0.20,0.80,0.30,0.60,0.90,0.15])
y_scores

array([0.95, 0.1 , 0.85, 0.4 , 0.2 , 0.8 , 0.3 , 0.6 , 0.9 , 0.15])

### Predictions with Different Thresholds

In [9]:
thresholds = [0.3, 0.5, 0.7]

for t in thresholds:
    y_pred_t = (y_scores >= t).astype(int)
    p = precision_score(y_true, y_pred_t)
    r = recall_score(y_true, y_pred_t)
    print(f"Threshold = {t}")
    print("Predictions:", y_pred_t)
    print("Precision :", round(p, 3))
    print("Recall    :", round(r, 3))
    print("-"*40)

Threshold = 0.3
Predictions: [1 0 1 1 0 1 1 1 1 0]
Precision : 0.714
Recall    : 1.0
----------------------------------------
Threshold = 0.5
Predictions: [1 0 1 0 0 1 0 1 1 0]
Precision : 0.8
Recall    : 0.8
----------------------------------------
Threshold = 0.7
Predictions: [1 0 1 0 0 1 0 0 1 0]
Precision : 1.0
Recall    : 0.8
----------------------------------------

### Observation

- **Lower threshold** → more positives predicted → **higher recall**, lower precision.
- **Higher threshold** → fewer positives predicted → **higher precision**, lower recall.

## 8. Compare Thresholds in a Table

In [10]:
rows = []

for t in np.arange(0.1, 1.0, 0.1):
    y_pred_t = (y_scores >= t).astype(int)
    rows.append({
        "Threshold": round(t,1),
        "Precision": round(precision_score(y_true, y_pred_t),3),
        "Recall": round(recall_score(y_true, y_pred_t),3),
        "F1": round(f1_score(y_true, y_pred_t),3)
    })

pd.DataFrame(rows)

   Threshold  Precision  Recall     F1
0        0.1      0.500     1.0  0.667
1        0.2      0.625     1.0  0.769
2        0.3      0.833     1.0  0.909
3        0.4      0.833     1.0  0.909
4        0.5      0.800     0.8  0.800
5        0.6      0.800     0.8  0.800
6        0.7      1.000     0.8  0.889
7        0.8      1.000     0.8  0.889
8        0.9      1.000     0.4  0.571

## 9. Manual Calculation Check

In [11]:
precision_manual = tp / (tp + fp)
recall_manual = tp / (tp + fn)
f1_manual = 2 * precision_manual * recall_manual / (precision_manual + recall_manual)

print("Precision manual:", round(precision_manual,3))
print("Recall manual   :", round(recall_manual,3))
print("F1 manual       :", round(f1_manual,3))

Precision manual: 0.8
Recall manual   : 0.8
F1 manual       : 0.8

The manual values should match scikit-learn results.

## 10. Real-World Interpretation

<Table columnSizing="equal" rowDivider={1}><Table.Row header><Table.Cell>Scenario</Table.Cell><Table.Cell align="end">What matters more?</Table.Cell></Table.Row><Table.Row><Table.Cell>Spam detection</Table.Cell><Table.Cell align="end">Precision</Table.Cell></Table.Row><Table.Row><Table.Cell>Fraud detection</Table.Cell><Table.Cell align="end">Recall</Table.Cell></Table.Row><Table.Row><Table.Cell>Disease screening</Table.Cell><Table.Cell align="end">Recall</Table.Cell></Table.Row><Table.Row><Table.Cell>Search engine top results</Table.Cell><Table.Cell align="end">Precision</Table.Cell></Table.Row><Table.Row><Table.Cell>Balanced business classifier</Table.Cell><Table.Cell align="end">F1 Score</Table.Cell></Table.Row></Table>

## Key Takeaways

- A **confusion matrix** summarizes prediction errors.
- **Precision** measures correctness of positive predictions.
- **Recall** measures how many actual positives were found.
- **F1-score** balances precision and recall.
- Changing the **decision threshold** changes precision and recall.
- There is usually a **trade-off** between precision and recall.
- Choose the metric based on the business problem, not just accuracy.

## Mini Practice

Try changing `y_scores` and rerun the threshold section:
1. Increase one score from `0.40` to `0.75`
2. Decrease one score from `0.85` to `0.45`
3. Observe how precision and recall change.

## What You Learned Today

<List gap={2}><List.Item>Confusion Matrix</List.Item><List.Item>TP, TN, FP, FN</List.Item><List.Item>Precision</List.Item><List.Item>Recall</List.Item><List.Item>F1 Score</List.Item><List.Item>Decision Threshold</List.Item><List.Item>Precision/Recall Trade-off</List.Item></List>

**Notebook completed: Day 19 - Performance Measures**